### ISSUE TITLE
Impressive!

### ISSUE THREAD

**Issue by X-Ryl669** [lvgl/lv_binding_js#1]
This is a huge work and impressive!

What would be excellent, would be to be able to run the same react code on the web (with or without building LVGL as a WASM module) and be able to build/compile the JS code to a native (or wasm) executable directly (via a WASM transformation, if it exists ?).

In that case, it would mean writing a code once that's using HTML/JS/CSS on the web (with true DOM components, not pseudo components in a canvas), and an almost 1:1 executable on the embedded system.

**Comment by Sxs7513** [comment]
Thank you. I am pleased you like it. 
Yes, technically you can binding any native ui component you want, even react-native can only runing on ios and android,   i dont think there will be a silver bullet for "write code once, run anywhere".

**Comment by derekstavis** [comment]
This sounds similar to #8, you should probably try that! Closing as a dupe
