### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by derekstavis** [lvgl/lv_binding_js#14]
I noticed that the current code is not using any formatting standards.

Prettier seem to be an opinionated and standard tool used across many projects. I would be glad to implement Prettier support on the repo and reformat all files so that editing code is a more pleasing experience. This should also ensure that all contributions are consistent in code style.

**Comment by kisvegabor** [comment]
Hi Derek,

This repo is a little bit abandoned now, and it would require a maintainer who can make such decisions. If you are interested in it I would be happy to invite you into this repo. Of course, it doesn't mean a life long full time engagement. Just answering issues and gardening the repo when it feels good.

If you would like to participate with some more work, I have some ideas how to make this binding not only hosted here but also promoted by LVGL. However, to do this promotion we need some tests, examples, and stable background here. 

What do you think?

**Comment by derekstavis** [comment]
The work done in this repo is spectacular to be honest, and I would love to contribute back to it so I can achieve my project's goals and advance this binding.

Glad you mentioned engagement, cause I don't want to make a commitment I'm not able to meet, but I'm willing to do my best to bring the library to completeness of components and make the dev experience better (I'm writing typescript types too for enhanced safety and dx)

**Comment by kisvegabor** [comment]
> What I'm willing to do is use some of my free time to bring the library to completeness of components and make the dev experience better (I'm writing TypeScript types too for enhanced safety and dx on my project).

So happy to hear that!  
I've just sent the invite. :hugs:

**Comment by kisvegabor** [comment]
I don't know much about React to decide which would be a good or bad idea.  So please, feel free to merge the PRs you feel appropriate.

**Comment by derekstavis** [comment]
Done in #16
