### ISSUE TITLE
Issue building for M1 Mac (arm64)

### ISSUE THREAD

**Issue by Frulko** [lvgl/lv_binding_js#2]
First of all : What a work, it's really awesome !
Thanks a lot, i look forward to work with it on project. :) 

I've tried to build on my M1 Macbook Pro, I followed the macOS instructions, I've updated the Makefile with the following code : 
```
dev-macos-arm:
	@mkdir -p $(DEV_ARM)
	cmake -B "$(DEV_ARM)" \
		-DCMAKE_BUILD_TYPE=Debug \
		-DCMAKE_BUILD_PLATFORM=arm64 \
		-DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@3 \
		-DOPENSSL_LIBRARIES=/opt/homebrew/opt/openssl@3/lib
	cmake --build $(DEV_ARM)
```
And after run : `make dev-macos-arm` all seems good but an error occured at 94% :
`lvgljs/src/deps/lv_drivers/display/fbdev.c:26:10: fatal error: 'linux/fb.h' file not found`

It's related to the framebuffer on linux but I'm on mac, I understand this is not completly related with your work but maybe you have an idea to handle that error for the compilation ?

Thanks again for your work !

**Comment by Sxs7513** [comment]
try this https://github.com/lvgl/lv_port_pc_eclipse/issues/51#issuecomment-544206194

file lv_drv_conf.h is in src/deps

**Comment by Chilus** [comment]
Before continuing this topic, what an impressive body of work!

Like @Frulko I'm also trying to build this on a M1 Mac, and managed to resolve the first framebuffer issue using [lvlg/lv_port_pc_eclipse#51 ](https://github.com/lvgl/lv_port_pc_eclipse/issues/51#issuecomment-544206194).

However, I got stuck on 96% with the following error:

```
lv_binding_js/src/deps/lv_drivers/indev/evdev.c:18:10: fatal error: 'linux/input.h' file not found
#include <linux/input.h>
```

I have updated the MakeFile with this:

```
dev-macos-arm:
	@mkdir -p $(DEV_ARM)
	cmake -B "$(DEV_ARM)" \
		-DCMAKE_BUILD_TYPE=Debug \
		-DCMAKE_BUILD_PLATFORM=arm64 \
		-DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@3 \
		-DOPENSSL_LIBRARIES=/opt/homebrew/opt/openssl@3/lib
	cmake --build $(DEV_ARM)
```

I have also tried to build with arm cross compiler tools like arm-linux-gnueabihf, but then I get issues with a missing -arch option, which is part of the Apple extensions to gcc.

Likewise, I also understand my question is not related to your work, but maybe you can point me in the right direction?

Thanks for your work!

**Comment by derekstavis** [comment]
Closing this as there's a new build system in master branch. Please open a new issue if this is still happening!
