### ISSUE TITLE
How to implement the function of page jump

### ISSUE THREAD

**Issue by ctfshining** [lvgl/lv_binding_js#24]
How to implement the function of page jump?
For example: when I click a button, The screen jump to another page.
Thank you!

**Comment by derekstavis** [comment]
This can be done using plain React:

```
const [page, setPage] = useState("home");

<Button onPress={() => setPage("profile")} />

...

if (page === "home") return <Home />
if (page === "profile") return <Profile />
```

If you want tabs and animations, check the widgets demo
