### ISSUE TITLE
Can we have a CRA-based example?

### ISSUE THREAD

**Issue by andreamancuso** [lvgl/lv_binding_js#28]
Thank you for making lvgl js bindings available to the open source community.

I was wondering if you could point me to a 'batteries-included' demo, maybe based on https://create-react-app.dev/ so that I can get a sense on how easy it is to embed LVGL in a browser?

Thanks!

**Comment by andreamancuso** [comment]
I opened src\render\react\components\Image\comp.js and noticed:

![image](https://github.com/lvgl/lv_binding_js/assets/19411542/fab3c12e-3886-4051-919f-772ce8834035)

I assume this is meant to be run on Node.js ? I suppose I got the wrong idea, i.e. this would work in a browser. Sorry if I'm being silly with these questions.

**Comment by KaruroChori** [comment]
No, it is running on an older version of txiki.js which is embedded in this repo. It cannot run on any other js runtime since bindings are platform specific.
You cannot have this embedded LVGL running in a browser, it si not meant for that.

**Comment by andreamancuso** [comment]
Understood, thanks for clarifying.

**Comment by andreamancuso** [comment]
For the avoidance of the doubt, I see you have added support for emscripten (in a separate repo) - can those bindings run in the browser using a <canvas> element?

**Comment by KaruroChori** [comment]
Are you referring to [this](https://github.com/KaruroChori/lv_binding_js/tree/txiki-runtime)?

**Comment by andreamancuso** [comment]
I have been busy developing 'React bindings' for Dear Imgui and egui. It's a big undertaking and I have no previous C++ or Rust experience, so I've been making mistakes and likely my code isn't the most performant (read: it needs a lot of work).

That said, I do have 2 very rough online demos (the Dear Imgui demo only works in Chrome and Edge, Firefox Nightlies).

https://andreamancuso.github.io/react-wasm/dear-imgui/

https://andreamancuso.github.io/react-wasm/egui/

I was hoping to achieve a similar result using the lv_binding_js package, or the emscripten one.

**Comment by derekstavis** [comment]
It seems your problem is solved so I'm closing this issue
