### ISSUE TITLE
Support MCU?

### ISSUE THREAD

**Issue by letanphuc** [lvgl/lv_binding_js#41]
Is there any plan to support this project to run on MCU like STM32 or NXP?

**Comment by KaruroChori** [comment]
txiki.js, the js runtime, requires an operating system supported by libuv to work. As long as you are not planning to run it baremetal it should be possible.

**Comment by derekstavis** [comment]
Running on bare metal MCU without a Linux operating system is not supported since this got migrated to txiki.js. I believe that it should be possible to port this back to `quickjs-ng` in case this is a required use-case.
