### ISSUE TITLE
issue for build-arm on device

### ISSUE THREAD

**Issue by HuangJC-cn** [lvgl/lv_binding_js#7]
Build with `make dev-arm` and running on linux+arm device is correct.

Build with `make build-arm` was crash when loading  `index.js`

log:
```shell
[User]  (2.542, +1)      ChartConstructor: Chart 33 created     (in chart_wrap.cpp line #666)
[User]  (2.543, +1)      NativeCompSetStyle: Chart 33 setStyle type 0   (in chart_wrap.cpp line #5)
[User]  (2.543, +0)      NativeCompSetDivLine: Chart 33 setDivLineCount 0 12    (in chart_wrap.cpp line #158)
[User]  (2.543, +0)      NativeCompSetPointNum: Chart 33 setPointNum 12         (in chart_wrap.cpp line #170)
[User]  (2.543, +0)      NativeCompSetLeftAxisOption: Chart 33 setLeftAxisOption        (in chart_wrap.cpp line #210)
[User]  (2.543, +0)      NativeCompSetLeftAxisData: Chart 33 setLeftAxisData    (in chart_wrap.cpp line #399)
[User]  (2.543, +0)      NativeCompSetBottomAxisOption: Chart 33 setBottomAxisOption    (in chart_wrap.cpp line #294)
Segmentation fault (core dumped)
```

No more information was available to analyze the crash.
And the next step in `dev-arm`  will run:
NativeCompSetStyle: `View 34 setStyle type 0    (in view_wrap.cpp line #5)`

**Comment by panjunweiby** [comment]
I'm having the same problem, how can I fix it

**Comment by panjunweiby** [comment]
@kisvegabor I'm having the same problem, how can I fix it

**Comment by panjunweiby** [comment]
@HuangJC-cn Do you fix this？

**Comment by j005u** [comment]
We're seeing the same issue on both some x86 hosts (but not all) and arm hosts.

**Comment by derekstavis** [comment]
It would be helpful to have a complete stack trace to find where this is happening

**Comment by ctfshining** [comment]
Debug(-g) works, Release not.

**Comment by derekstavis** [comment]
There's a new build system in the master branch. Please open a new issue if it is not working on a Linux system.
